/**
 * k6 script generator — the second pluggable engine beside JMeter.
 * Produces a self-contained k6 JavaScript file from the same test definition:
 * same four modes, same CSV placeholder substitution (${column}), same intent.
 * All user strings are embedded via JSON.stringify, so nothing can escape
 * into executable code.
 */

function stages(test) {
  const vu = test.virtual_users, ramp = test.ramp_up_secs, dur = test.duration_secs;
  switch (test.mode) {
    case "stress": // pressure rises the whole run
      return [{ duration: `${dur}s`, target: vu }];
    case "spike": {
      const baseline = Math.max(1, Math.round(vu * 0.2));
      const pre = Math.floor(dur * 0.4), hold = Math.floor(dur * 0.4);
      return [
        { duration: `${ramp}s`, target: baseline },
        { duration: `${Math.max(1, pre - ramp)}s`, target: baseline },
        { duration: "5s", target: vu },                    // the burst
        { duration: `${hold}s`, target: vu },
        { duration: `${Math.max(1, dur - pre - hold - 5)}s`, target: baseline },
      ];
    }
    case "soak":
    case "load":
    default:
      return [
        { duration: `${ramp}s`, target: vu },
        { duration: `${Math.max(1, dur - ramp)}s`, target: vu },
      ];
  }
}

function csvRows(csvData) {
  if (!csvData) return [];
  const lines = csvData.trim().split("\n");
  const cols = lines.shift().split(",").map((c) => c.trim());
  return lines
    .filter((l) => l.trim())
    .map((l) => {
      const vals = l.split(",");
      return Object.fromEntries(cols.map((c, i) => [c, (vals[i] ?? "").trim()]));
    });
}

export function generateK6Script(test) {
  const rows = csvRows(test.csv_data);
  const hasBody = test.method !== "GET" && test.method !== "HEAD" && test.body;
  return `// Generated by Loadstar — engine: k6 — mode: ${test.mode}
import http from 'k6/http';
import { check, sleep } from 'k6';
const DEBUG = ${test.debug ? "true" : "false"};

const URL = ${JSON.stringify(test.target_url)};
const METHOD = ${JSON.stringify(test.method || "GET")};
const HEADERS = ${JSON.stringify(test.headers || {})};
const BODY = ${hasBody ? JSON.stringify(test.body) : "null"};
const DATA = ${JSON.stringify(rows)};
const BASE = ${JSON.stringify(test.target_url)};
const REQUESTS = ${JSON.stringify(
      test.requests && test.requests.length
        ? test.requests.map((r) => ({ name: r.name || (r.method + " " + (r.path||"/")), method: r.method || "GET", path: r.path || "/", headers: r.headers || {}, body: (r.method !== "GET" && r.method !== "HEAD") ? (r.body || null) : null, extract: r.extract || null, assert: r.assert || null, think_time_ms: Number(r.think_time_ms) > 0 ? Number(r.think_time_ms) : 0, think_time_jitter_pct: Number(r.think_time_jitter_pct) > 0 ? Math.min(Number(r.think_time_jitter_pct), 90) : 0 }))
        : [{ name: (test.method||"GET") + " " + test.target_url, method: test.method || "GET", path: null, headers: test.headers || {}, body: hasBody ? test.body : null }]
    )};

// \${column} placeholder substitution from CSV rows
function sub(s, row) {
  if (!s || !row) return s;
  return s.replace(/\\$\\{(\\w+)\\}/g, (_, k) => (row[k] != null ? row[k] : ''));
}

// Substitute \${var} using values captured from earlier responses (response chaining).
function subCaptured(s, captured) {
  if (!s) return s;
  return s.replace(/\\$\\{(\\w+)\\}/g, (m, k) => (k in captured ? captured[k] : m));
}
// Pull a value out of a response per the request's extract config.
function extractValue(res, ex) {
  try {
    if (ex.source === 'json') {
      const path = (ex.path || '').replace(/^\\$\\.?/, '');
      let v = res.json();
      for (const part of path.split('.').filter(Boolean)) v = v == null ? v : v[part];
      return v == null ? '' : String(v);
    }
    if (ex.source === 'header') {
      const name = ex.path || '';
      if (res.cookies && res.cookies[name] && res.cookies[name][0]) return res.cookies[name][0].value;
      return res.headers[name] || '';
    }
    if (ex.source === 'regex') {
      const m = new RegExp(ex.path || '').exec(res.body || '');
      return m ? (m[1] != null ? m[1] : m[0]) : '';
    }
  } catch (e) { return ''; }
  return '';
}

export const options = ${test.debug ? JSON.stringify({ vus: 1, iterations: 1 }) : `{\n  stages: ${JSON.stringify(stages(test), null, 2)},\n}`};

export default function () {
  const row = DATA.length ? DATA[(__VU - 1 + __ITER) % DATA.length] : null;
  // captured: per-iteration store for response-chaining (login token, session id, etc.)
  // k6 keeps a per-VU cookie jar automatically, so Set-Cookie replays for free (Phase A).
  const captured = {};
  const merge = (s) => sub(subCaptured(s, captured), row);
  for (const req of REQUESTS) {
    const url = req.path == null ? merge(BASE) : merge(BASE.replace(/\\/$/, '') + req.path);
    const headers = {};
    for (const k in (req.headers || {})) headers[k] = merge(req.headers[k]);
    /* If the request ASSERTS a status, that status is EXPECTED — k6 must not count
       it as a failure. Without this, a deliberate 404 test inflates error_rate, and
       error_rate is what the SLA gate keys off: Loadstar would fail a CI pipeline
       over a test that is working perfectly.

       PER-REQUEST, deliberately. A global expectedStatuses would make EVERY request
       accept 404, so a REAL 404 on the root path would silently pass. Same disease, opposite
       direction. */
    /* The 'asserted' tag tells parseK6 that this request has its OWN verdict. Without it the
       parser cannot distinguish 'the server was unreachable' from 'the server answered
       with a status we asserted against' — and it would count a correctness failure as
       an outage. k6 has TWO independent verdicts (http_req_failed and checks) where
       JMeter has one; this reconciles them. */
    const asserted = !!(req.assert && req.assert.status != null);
    const opts = { headers, timeout: '30s', tags: { name: req.name, asserted: String(asserted) } };
    if (req.assert && req.assert.status != null) {
      opts.responseCallback = http.expectedStatuses(req.assert.status);
    }
    const res = http.request(req.method, url, req.body ? merge(req.body) : null, opts);
    const checks = {};
    if (req.assert) {
      if (req.assert.status != null) checks['status == ' + req.assert.status] = (r) => r.status === req.assert.status;
      if (req.assert.body_contains) checks['body contains "' + req.assert.body_contains + '"'] = (r) => (r.body || '').includes(req.assert.body_contains);
      if (req.assert.body_excludes) checks['body excludes "' + req.assert.body_excludes + '"'] = (r) => !(r.body || '').includes(req.assert.body_excludes);
      if (req.assert.header_name && req.assert.header_contains) {
        checks['header ' + req.assert.header_name + ' contains "' + req.assert.header_contains + '"'] = (r) => {
          const want = req.assert.header_name.toLowerCase();
          let val = '';
          for (const k in (r.headers || {})) { if (k.toLowerCase() === want) { val = r.headers[k]; break; } }
          return String(val).includes(req.assert.header_contains);
        };
      }
    }
    /* WAS: an invented 'status is 2xx/3xx' check when the user declared none.
       That reported assertion_total = total_requests on a test WITH NO ASSERTIONS —
       a fabricated measurement — and double-counted every failure (once as an error,
       once as an assertion failure). JMeter has no equivalent, so the two engines
       reported DIFFERENT TRUTHS for the same test. It is also redundant:
       http_req_failed already reports exactly 'was this 2xx/3xx'.

       An assertion the user never wrote is not an assertion. */
    if (Object.keys(checks).length) check(res, checks);
    if (DEBUG) {
      console.log('__TRACE__' + JSON.stringify({
        name: req.name || (req.method + ' ' + (req.path || '/')),
        method: req.method, url: url,
        reqHeaders: headers, reqBody: req.body ? merge(req.body) : null,
        status: res.status, resHeaders: res.headers,
        resBody: (res.body || '').slice(0, 4000),
        extract: (req.extract && req.extract.var) ? req.extract.var : null,
      }));
    }
    // Phase B: capture a value from this response for use in later requests.
    if (req.extract && req.extract.var) {
      captured[req.extract.var] = extractValue(res, req.extract);
      if (DEBUG) console.log('__CAPTURED__' + JSON.stringify({ var: req.extract.var, value: captured[req.extract.var] }));
    }
    // Think time: pause like a real user reading the page. Jitter avoids
    // every VU firing in lockstep (an unrealistic thundering herd).
    if (req.think_time_ms > 0) {
      const jit = req.think_time_jitter_pct > 0 ? req.think_time_jitter_pct / 100 : 0;
      const factor = jit > 0 ? (1 - jit) + (Math.random() * 2 * jit) : 1;
      const ms = Math.max(0, req.think_time_ms * factor);
      sleep(ms / 1000);
    }
  }
}
`;
}

